from uuid import UUID
from enum import Enum
from typing import Annotated, Optional
from pydantic import BaseModel, Field, StringConstraints


class RequestStatus(str, Enum):
    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"

class ApplicationRequest(BaseModel):
    user_input: Annotated[
        str,
        StringConstraints(strip_whitespace=True, min_length=1),
    ] = Field(..., description="The input text for the application request")
    request_id: UUID = Field(
        ...,
        description="Unique identifier for the application request"
    )

class ApplicationResult(BaseModel):
    request_id: UUID = Field(
        ...,
        description="Unique identifier for the application request"
    )
    status: RequestStatus = Field(
        ...,
        description="The current status of the application request"
    )
    provider: str = Field(
        ...,
        description="The name of the provider used to generate the output text"
    )
    model: str = Field(
        ...,
        description="The name of the model used to generate the output text"
    )
    text: str = Field(
        ...,
        description="The output text generated by the application's LLM"
    )
    latency: float = Field(
        ...,
        description="The time taken to generate the output text in seconds"
    )
    input_tokens: Optional[int] = Field(
        None,
        description="The number of tokens in the input text"
    )
    output_tokens: Optional[int] = Field(
        None,
        description="The number of tokens in the output text"
    )